/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Modul2;

import javax.swing.JOptionPane;

/**
 *
 * @author unbk
 */
public class FWarung extends javax.swing.JFrame {

    /**
     * Creates new form FWarung
     */
    public FWarung() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        CaraBayar = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        chkSoto = new javax.swing.JCheckBox();
        chkSate = new javax.swing.JCheckBox();
        chkEsJeruk = new javax.swing.JCheckBox();
        chkEsTeh = new javax.swing.JCheckBox();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        rdoCash = new javax.swing.JRadioButton();
        rdoBCA = new javax.swing.JRadioButton();
        rdoMandiri = new javax.swing.JRadioButton();
        lblCaraBayar = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtSoto = new javax.swing.JTextField();
        txtSate = new javax.swing.JTextField();
        txtEsJeruk = new javax.swing.JTextField();
        txtEsTeh = new javax.swing.JTextField();
        btnHitung = new javax.swing.JButton();
        btnKosong = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel1.setText("Menu");

        chkSoto.setText("Soto: Rp. 10.000");
        chkSoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSotoActionPerformed(evt);
            }
        });

        chkSate.setText("Sate: Rp. 10.000");
        chkSate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkSateActionPerformed(evt);
            }
        });

        chkEsJeruk.setText("Es Jeruk: Rp. 5.000");
        chkEsJeruk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkEsJerukActionPerformed(evt);
            }
        });

        chkEsTeh.setText("Es Teh: Rp. 3.000");
        chkEsTeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkEsTehActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 12)); // NOI18N
        jLabel2.setText("Cara Bayar:");

        CaraBayar.add(rdoCash);
        rdoCash.setSelected(true);
        rdoCash.setText("Uang Cash");
        rdoCash.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoCashActionPerformed(evt);
            }
        });

        CaraBayar.add(rdoBCA);
        rdoBCA.setText("BCA Card");
        rdoBCA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoBCAActionPerformed(evt);
            }
        });

        CaraBayar.add(rdoMandiri);
        rdoMandiri.setText("Mandiri Card");
        rdoMandiri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoMandiriActionPerformed(evt);
            }
        });

        lblCaraBayar.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblCaraBayar.setText("Cara Bayar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rdoCash)
                    .addComponent(rdoBCA)
                    .addComponent(rdoMandiri)))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addContainerGap(44, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lblCaraBayar)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(13, 13, 13)
                .addComponent(rdoCash)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdoBCA)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rdoMandiri)
                .addGap(18, 18, 18)
                .addComponent(lblCaraBayar)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel3.setText("Quantity");

        txtSoto.setEditable(false);
        txtSoto.setText("0");
        txtSoto.setEnabled(false);

        txtSate.setEditable(false);
        txtSate.setText("0");
        txtSate.setEnabled(false);

        txtEsJeruk.setEditable(false);
        txtEsJeruk.setText("0");
        txtEsJeruk.setEnabled(false);

        txtEsTeh.setEditable(false);
        txtEsTeh.setText("0");
        txtEsTeh.setEnabled(false);
        txtEsTeh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEsTehActionPerformed(evt);
            }
        });

        btnHitung.setText("Hitung");
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        btnKosong.setText("Kosongkan");
        btnKosong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKosongActionPerformed(evt);
            }
        });

        lblTotal.setFont(new java.awt.Font("Verdana", 1, 14)); // NOI18N
        lblTotal.setText("Rp. 0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(chkSoto)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtSoto, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(112, 112, 112))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkEsTeh)
                            .addComponent(chkEsJeruk)
                            .addComponent(chkSate))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 112, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSate, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEsJeruk, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtEsTeh, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(btnHitung, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(lblTotal))
                        .addGap(48, 48, 48))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnKosong)
                .addGap(39, 39, 39))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkSoto)
                    .addComponent(txtSoto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkSate)
                    .addComponent(txtSate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkEsJeruk)
                    .addComponent(txtEsJeruk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(chkEsTeh)
                    .addComponent(txtEsTeh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 75, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnHitung)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTotal)
                        .addGap(46, 46, 46)
                        .addComponent(btnKosong)
                        .addGap(29, 29, 29))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void chkEsJerukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkEsJerukActionPerformed
        // TODO add your handling code here:
        if(chkEsJeruk.isSelected()) {
            txtEsJeruk.setEditable(true);
            txtEsJeruk.setEnabled(true);
            txtEsJeruk.setText("1");
        } else {
            txtEsJeruk.setEditable(false);
            txtEsJeruk.setEnabled(false);
            txtEsJeruk.setText("0");
        }
    }//GEN-LAST:event_chkEsJerukActionPerformed

    private void chkEsTehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkEsTehActionPerformed
        // TODO add your handling code here:
        if(chkEsTeh.isSelected()) {
            txtEsTeh.setEditable(true);
            txtEsTeh.setEnabled(true);
            txtEsTeh.setText("1");
        } else {
            txtEsTeh.setEditable(false);
            txtEsTeh.setEnabled(false);
            txtEsTeh.setText("0");
        }
    }//GEN-LAST:event_chkEsTehActionPerformed

    private void rdoCashActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoCashActionPerformed
        // TODO add your handling code here:
        if(rdoCash.isSelected()) {
            lblCaraBayar.setText("Uang Cash");
        }
    }//GEN-LAST:event_rdoCashActionPerformed

    private void rdoMandiriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoMandiriActionPerformed
        // TODO add your handling code here:
         if(rdoMandiri.isSelected()) {
            lblCaraBayar.setText("Mandiri Card");
        }
    }//GEN-LAST:event_rdoMandiriActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        // TODO add your handling code here:
        boolean IDataOke = true; 
        
        if (chkSate.isSelected() && txtSate.getText() == " ")
            IDataOke = false;
        if (chkEsJeruk.isSelected() && txtEsJeruk.getText() == " ")
            IDataOke = false;
        if (chkEsJeruk.isSelected() && txtEsJeruk.getText() == " ")
            IDataOke = false;
        if (chkEsJeruk.isSelected() && txtEsJeruk.getText() == " ")
            IDataOke = false;
        //Mengecek status pesanan, apakah ada atau tdk
        
        if (!IDataOke) {
            JOptionPane.showMessageDialog(this, "Kesalahan");
        } else {
            //deklarasi
            int nSoto = Integer.parseInt(txtSoto.getText());
            int nSate = Integer.parseInt(txtSate.getText());
            int nEsJeruk = Integer.parseInt(txtEsJeruk.getText());
            int nEsTeh = Integer.parseInt(txtEsTeh.getText());
            
            //rumus
            int nTotal =(10000*nSoto) + (10000*nSate) + (5000*nEsJeruk) + (3000*nEsTeh);
            lblTotal.setText("Rp. " + nTotal);
            
            //BAgian utk menampilkan cara bayar
            /*if (rdoCash.isSelected())
                lblCaraBayar.setText(rdoCash.getActionCommand());
            if (rdoMandiri.isSelected())
                lblCaraBayar.setText(rdoMandiri.getActionCommand());
            if (rdoBCA.isSelected())
                lblCaraBayar.setText(rdoBCA.getActionCommand());*/
        }
    }//GEN-LAST:event_btnHitungActionPerformed

    private void chkSotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSotoActionPerformed
        // TODO add your handling code here:
        if(chkSoto.isSelected()) {
            txtSoto.setEditable(true);
            txtSoto.setEnabled(true);
            txtSoto.setText("1");
        } else {
            txtSoto.setEditable(false);
            txtSoto.setEnabled(false);
            txtSoto.setText("0");
        }
    }//GEN-LAST:event_chkSotoActionPerformed

    private void chkSateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkSateActionPerformed
        // TODO add your handling code here:
        if(chkSate.isSelected()) {
            txtSate.setEditable(true);
            txtSate.setEnabled(true);
            txtSate.setText("1");
        } else {
            txtSate.setEditable(false);
            txtSate.setEnabled(false);
            txtSate.setText("0");
        }
    }//GEN-LAST:event_chkSateActionPerformed

    private void btnKosongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKosongActionPerformed
        // TODO add your handling code here:
        chkSoto.setSelected(false);
        txtSoto.setEditable(false);
        txtSoto.setEnabled(false);
        txtSoto.setText("0");
        chkSate.setSelected(false);
        txtSate.setEditable(false);
        txtSate.setEnabled(false);
        txtSate.setText("0");
        chkEsTeh.setSelected(false);
        txtEsTeh.setEditable(false);
        txtEsTeh.setEnabled(false);
        txtEsTeh.setText("0");
        chkEsJeruk.setSelected(false);
        txtEsJeruk.setEditable(false);
        txtEsJeruk.setEnabled(false);
        txtEsJeruk.setText("0");
        rdoCash.setSelected(true);
        lblCaraBayar.setText("Uang Cash");
        lblTotal.setText("Rp. ");
    }//GEN-LAST:event_btnKosongActionPerformed

    private void rdoBCAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoBCAActionPerformed
        // TODO add your handling code here:
         if(rdoBCA.isSelected()) {
            lblCaraBayar.setText("BCA Card");
        }
    }//GEN-LAST:event_rdoBCAActionPerformed

    private void txtEsTehActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEsTehActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEsTehActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FWarung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FWarung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FWarung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FWarung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FWarung().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup CaraBayar;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnKosong;
    private javax.swing.JCheckBox chkEsJeruk;
    private javax.swing.JCheckBox chkEsTeh;
    private javax.swing.JCheckBox chkSate;
    private javax.swing.JCheckBox chkSoto;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCaraBayar;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JRadioButton rdoBCA;
    private javax.swing.JRadioButton rdoCash;
    private javax.swing.JRadioButton rdoMandiri;
    private javax.swing.JTextField txtEsJeruk;
    private javax.swing.JTextField txtEsTeh;
    private javax.swing.JTextField txtSate;
    private javax.swing.JTextField txtSoto;
    // End of variables declaration//GEN-END:variables
}
