/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Modul2;

/**
 *
 * @author ADMIN
 */
public class Tugas_modul2 extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Tugas_modul2.class.getName());

    /**
     * Creates new form Tugas_modul2
     */
    public Tugas_modul2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Seks = new javax.swing.ButtonGroup();
        lblNama = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        lblGPokok = new javax.swing.JLabel();
        lblSeks = new javax.swing.JLabel();
        lblStatus = new javax.swing.JLabel();
        lblJmlhAnak = new javax.swing.JLabel();
        txtJmlhAnak = new javax.swing.JTextField();
        txtGaji = new javax.swing.JTextField();
        rdoPria = new javax.swing.JRadioButton();
        rdoWanita = new javax.swing.JRadioButton();
        chkmenikah = new javax.swing.JCheckBox();
        lblpasangan = new javax.swing.JLabel();
        txtnamapasangan = new javax.swing.JTextField();
        btnTotal = new javax.swing.JButton();
        lblTotal = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblNama.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        lblNama.setText("Nama Pegawai");

        lblGPokok.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        lblGPokok.setText("Gaji Pokok");

        lblSeks.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        lblSeks.setText("Seks");

        lblStatus.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        lblStatus.setText("Status");

        lblJmlhAnak.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        lblJmlhAnak.setText("Jumlah Anak");

        txtJmlhAnak.setEditable(false);
        txtJmlhAnak.setEnabled(false);
        txtJmlhAnak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJmlhAnakActionPerformed(evt);
            }
        });

        txtGaji.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtGajiActionPerformed(evt);
            }
        });

        Seks.add(rdoPria);
        rdoPria.setText("Pria");
        rdoPria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoPriaActionPerformed(evt);
            }
        });

        Seks.add(rdoWanita);
        rdoWanita.setText("Wanita");
        rdoWanita.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rdoWanitaActionPerformed(evt);
            }
        });

        chkmenikah.setText("Menikah");
        chkmenikah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkmenikahActionPerformed(evt);
            }
        });

        lblpasangan.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        lblpasangan.setText("Nama Suami");

        btnTotal.setText("HItung Gaji Total");
        btnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalActionPerformed(evt);
            }
        });

        lblTotal.setFont(new java.awt.Font("Verdana", 1, 11)); // NOI18N
        lblTotal.setText("Gaji Total");

        txtTotal.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblStatus)
                    .addComponent(lblNama)
                    .addComponent(lblGPokok)
                    .addComponent(btnTotal)
                    .addComponent(lblSeks)
                    .addComponent(lblpasangan)
                    .addComponent(lblTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtnama, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtGaji, javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(lblJmlhAnak)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtJmlhAnak, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtnamapasangan)
                    .addComponent(txtTotal)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(rdoPria)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rdoWanita))
                            .addComponent(chkmenikah, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(178, 178, 178))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNama)
                    .addComponent(txtnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblGPokok)
                    .addComponent(txtGaji, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblSeks)
                    .addComponent(rdoPria)
                    .addComponent(rdoWanita))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblStatus)
                    .addComponent(chkmenikah))
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJmlhAnak)
                    .addComponent(txtJmlhAnak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblpasangan)
                    .addComponent(txtnamapasangan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnTotal)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotal)
                    .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtGajiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtGajiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtGajiActionPerformed

    private void rdoPriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoPriaActionPerformed
        // TODO add your handling code here:
        if (rdoPria.isSelected()) {
            lblpasangan.setText("Nama Istri");
        }
    }//GEN-LAST:event_rdoPriaActionPerformed

    private void btnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalActionPerformed
        // TODO add your handling code here:
        
        double gajiPokok = Double.parseDouble(txtGaji.getText());
        double jmlhanak = 0;
        if (chkmenikah.isSelected()) {
            jmlhanak = Double.parseDouble(txtJmlhAnak.getText());
        } else {
            jmlhanak = 0;
        }
        if (jmlhanak >= 0 && jmlhanak <= 3) {
            if (jmlhanak == 3) {
            double gajiTotal = gajiPokok + (gajiPokok * 10/100 * 3);
            txtTotal.setText(Double.toString(gajiTotal));
            } else {
            double gajiTotal = gajiPokok + (gajiPokok * 10/100 * jmlhanak);
            txtTotal.setText(Double.toString(gajiTotal));
            }
        } else {
            txtTotal.setText("Error, check your input");
        }
        
    }//GEN-LAST:event_btnTotalActionPerformed

    private void chkmenikahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkmenikahActionPerformed
        // TODO add your handling code here:
        if (chkmenikah.isSelected()) {
            txtJmlhAnak.setEditable(true);
            txtJmlhAnak.setEnabled(true);
        } else {
            txtJmlhAnak.setEditable(false);
            txtJmlhAnak.setEnabled(false);
        }
    }//GEN-LAST:event_chkmenikahActionPerformed

    private void rdoWanitaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rdoWanitaActionPerformed
        // TODO add your handling code here:
        if (rdoWanita.isSelected()) {
            lblpasangan.setText("Nama Suami");
        }
    }//GEN-LAST:event_rdoWanitaActionPerformed

    private void txtJmlhAnakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJmlhAnakActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJmlhAnakActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Tugas_modul2().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup Seks;
    private javax.swing.JButton btnTotal;
    private javax.swing.JCheckBox chkmenikah;
    private javax.swing.JLabel lblGPokok;
    private javax.swing.JLabel lblJmlhAnak;
    private javax.swing.JLabel lblNama;
    private javax.swing.JLabel lblSeks;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JLabel lblTotal;
    private javax.swing.JLabel lblpasangan;
    private javax.swing.JRadioButton rdoPria;
    private javax.swing.JRadioButton rdoWanita;
    private javax.swing.JTextField txtGaji;
    private javax.swing.JTextField txtJmlhAnak;
    private javax.swing.JTextField txtTotal;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txtnamapasangan;
    // End of variables declaration//GEN-END:variables
}
